name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '9.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build_and_push:
        runs-on:  ubuntu-24.04-arm
        permissions:
          contents: read
          packages: write        
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build umbracalendar.site Image'
            run: |
              docker buildx build . --platform=linux/arm64 --tag ghcr.io/nul800sebastiaan/umbracalendar.site:latest
              docker push ghcr.io/nul800sebastiaan/umbracalendar.site:latest


